FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o kubekitty-controller ./cmd/controller/main.go

FROM alpine:3.18
WORKDIR /
COPY --from=builder /app/kubekitty-controller .
COPY --from=builder /app/rules /etc/kubekitty/rules

ENTRYPOINT ["/kubekitty-controller"]